### ISSUE TITLE
ipdSummary : "Exception: Invalid type to getFileHandle"

### ISSUE THREAD

**Issue by wilfriedguiblet** [PacificBiosciences/kineticsTools#12]
Hello everyone,

I am trying to extract the IPD values from an alignment I did using pbalign. Here is the command I used to align my reads:

$pbalign --nproc 16 --forQuiver --metrics IPD,DeletionQV,InsertionQV reads.bax.h5 ref.fasta test.cmp.h5

I am then using ipdSummary.py  as such:

$ipdSummary.py test.cmp.h5

However, I obtain this error:

 File 
"/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/base.py", line 65, in getFileHandle
    raise Exception("Invalid type to getFileHandle")
Exception: Invalid type to getFileHandle

Am I doing anything wrong here?

Thank you for your help,

**Comment by eltonjrv** [comment]
Hello guys,

I am having that same error with the following command line:
**$ nice ipdSummary.py --outfile baxh5-vs-Sm_v5p2.ipdSummary --numWorkers 20 -v baxh5-vs-Sm_v5p2.cmp.h5 1>ipdSummary.log 2>ipdSummary.err &
$ cat ipdSummary.err**
Traceback (most recent call last):
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/ipdSummary.py", line 692, in main
    rcode = kt.start()
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/ipdSummary.py", line 342, in start
    return self.run()
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/ipdSummary.py", line 405, in run
    ret = self._mainLoop()
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/ipdSummary.py", line 619, in _mainLoop
    self.loadReferenceAndModel(self.args.reference, self.args.infile)
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/ipdSummary.py", line 531, in loadReferenceAndModel
    contigs = ReferenceUtils.loadReferenceContigs(referencePath, cmpH5Path)
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/ReferenceUtils.py", line 46, in loadReferenceContigs
    fastaReader = FastaReader(referencePath)
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/base.py", line 72, in __init__
    self.file = getFileHandle(f, "r")
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/base.py", line 65, in getFileHandle
    raise Exception("Invalid type to getFileHandle")
Exception: Invalid type to getFileHandle
Traceback (most recent call last):
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/ipdSummary.py", line 715, in <module>
    sys.exit(main())
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/ipdSummary.py", line 692, in main
    rcode = kt.start()
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/ipdSummary.py", line 342, in start
    return self.run()
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/ipdSummary.py", line 405, in run
    ret = self._mainLoop()
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/ipdSummary.py", line 619, in _mainLoop
    self.loadReferenceAndModel(self.args.reference, self.args.infile)
  File "/work/schisto/elton/smrtanalysis/current/analysis/bin/ipdSummary.py", line 531, in loadReferenceAndModel
    contigs = ReferenceUtils.loadReferenceContigs(referencePath, cmpH5Path)
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/ReferenceUtils.py", line 46, in loadReferenceContigs
    fastaReader = FastaReader(referencePath)
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/base.py", line 72, in __init__
    self.file = getFileHandle(f, "r")
  File "/work/schisto/elton/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/base.py", line 65, in getFileHandle
    raise Exception("Invalid type to getFileHandle")
Exception: Invalid type to getFileHandle

Can anyone shed some light to solve this issue?
Thanks in advance.
Cheers,
Elton

**Comment by eltonjrv** [comment]
Sorry, my bad!
I solved that issue adding the reference genome on the command line (with the --reference option).
Nevertheless, now I got a new error message.
I'll open another issue with that log.
Thanks!
