### ISSUE TITLE
Is kineticsTools an installable and command-line-used methods

### ISSUE THREAD

**Issue by qihualiang** [PacificBiosciences/kineticsTools#13]
I have been searching around for methods to detect methylation based on .bax.h5/.cmp.h5 data, and it seems that kineticsTools is the ideal method. However, all documentations don't seem to include parts of installation or command lines examples. 
Is this method only a python package that I need to write my own python code step by step? Or is there any well-writen program?

**Comment by mhsieh** [comment]
Normally this tool is provided by a smrtanalysis installation. Documentation is provided here https://github.com/PacificBiosciences/kineticsTools/blob/master/doc/manual.rst .

**Comment by qihualiang** [comment]
@mhsieh Thank you Mengjuei!

I know that I can use kineticsTools and put .cmp.h5 as input (which I have already got). But the protocols from your site or here https://github.com/PacificBiosciences/Bioinformatics-Training/wiki/Methylome-Analysis-Technical-Note  are not using any command lines as illustration. 

I am running this analysis on a linux platform and I want to know what is running and how to run it in some command lines.

**Comment by mhsieh** [comment]
Richard already helped you on SeqAnswers, but I can provide some more details. The best way to learn what command has been run is to run a demo jobs according to the document, and dig into the job folder and check the scripts. We can help you finding the necessary information.

**Comment by qihualiang** [comment]
Thank you!
Now I am trying to run ipdSummary.py as 
ipdSummary.py --reference ReferenceGenome.fasta example1.cmp.h5

But there are below error messages:
---------------------
Traceback (most recent call last):
  File "/home/qliang/0.soft/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/ipdSummary.py", line 715, in <module>
    sys.exit(main())
  File "/home/qliang/0.soft/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/ipdSummary.py", line 692, in main
    rcode = kt.start()
  File "/home/qliang/0.soft/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/ipdSummary.py", line 342, in start
    return self.run()
  File "/home/qliang/0.soft/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/ipdSummary.py", line 405, in run
    ret = self._mainLoop()
  File "/home/qliang/0.soft/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/ipdSummary.py", line 619, in _mainLoop
    self.loadReferenceAndModel(self.args.reference, self.args.infile)
  File "/home/qliang/0.soft/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/ipdSummary.py", line 531, in loadReferenceAndModel
    contigs = ReferenceUtils.loadReferenceContigs(referencePath, cmpH5Path)
  File "/home/qliang/software/python/lib/python2.7/site-packages/kineticsTools-0.5.1-py2.7-linux-x86_64.egg/kineticsTools/ReferenceUtils.py", line 70, in loadReferenceContigs
    for x in alignmentSet.referenceInfoTable:
AttributeError: 'str' object has no attribute 'referenceInfoTable'

--------------
Is there any required format of the reference besides of FASTA?

**Comment by vivekiitkgp** [comment]
Hi @mhsieh 

I think it'd be great to have a few command line examples (or API reference) of running kineticsTools. The manual documentation doesn't help much in this regard.

Thank you!

**Comment by mhsieh** [comment]
Not a basemod expert here, but I suppose you can look into the job directory, and you can find commands called for the workflow.

**Comment by mhsieh** [comment]
@qihualiang sorry we missed your question for some reason, but the error you have indicates that you are mixing smrtanalysis 2.3.0 installation with your own python environment. If that's not what you intended to do, please use a clean account and run `/home/qliang/0.soft/smrtanalysis/smrtcmds/bin/smrtwrap ipdSummary.py` instead ipdSummary.py directly.

We can then look into what might have been causing the issue you have with the commands.
