### ISSUE TITLE
ipdSummary KeyError related to Reference

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/kineticsTools#20]
Hi,

I am trying to produce the base modficiation .gff and .csv files with the following command:

`ipdSummary  input.cmp.h5 --reference pDmeth.fa --gff ipd.modifications.gff --csv ipd.modifications.csv`

However, I am getting the following error message:

```
'pDmeth'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pbcommand-0.3.25-py2.7.egg/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ipdSummary.py", line 702, in args_runner
    return kt.start()
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ipdSummary.py", line 385, in start
    return self.run()
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ipdSummary.py", line 447, in run
    ret = self._mainLoop()
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ipdSummary.py", line 612, in _mainLoop
    self.loadReferenceAndModel(self.args.reference)
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ipdSummary.py", line 539, in loadReferenceAndModel
    alignmentSet=self._sharedAlignmentSet)
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ReferenceUtils.py", line 71, in loadReferenceContigs
    contigDict[x.FullName].cmph5ID = x.ID
KeyError: 'pDmeth'
2016-05-03 17:45:32,976 [ERROR] 'pDmeth'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pbcommand-0.3.25-py2.7.egg/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ipdSummary.py", line 702, in args_runner
    return kt.start()
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ipdSummary.py", line 385, in start
    return self.run()
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ipdSummary.py", line 447, in run
    ret = self._mainLoop()
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ipdSummary.py", line 612, in _mainLoop
    self.loadReferenceAndModel(self.args.reference)
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ipdSummary.py", line 539, in loadReferenceAndModel
    alignmentSet=self._sharedAlignmentSet)
  File "/usr/local/lib/python2.7/site-packages/kineticsTools-0.5.2-py2.7-macosx-10.11-x86_64.egg/kineticsTools/ReferenceUtils.py", line 71, in loadReferenceContigs
    contigDict[x.FullName].cmph5ID = x.ID
KeyError: 'pDmeth'
```

I can successfully use R-kinetics on the .cmp.h5 file, so the base modification information should be successfully loaded.

Can you please help me troubleshoot?

Thanks,
Charles

**Comment by mhsieh** [comment]
we normally don't support kineticsTools at all outside of smrtportal, have you tried running this with a smrtportal installation?

**Comment by cwarden45** [comment]
I currently don't have smrtportal access (it looks like there is an account for me on the server, but I can't reset my password).

While part of my current goal is to test command line tools without smrtportal access, I would also like it if I can get smrtportal access.  Unless you know of a general solution, I will check with my supervisor to see if there is a rep that can help with our server.

**Comment by mhsieh** [comment]
You dont need to create a new account for the installation nor root access. You don't even need to run the server demon.

**Comment by mhsieh** [comment]
for more information, start from here. https://github.com/mhsieh/SMRTAnalysis_2.3.0_install/tree/master/vagrant-u1404

**Comment by cwarden45** [comment]
OK, thanks - I will take a look at that code and see if I can run the smrtportal commands from my mac.

**Comment by mhsieh** [comment]
Do note that you will need a linux for a smrtanalysis installation. Here I use vagrant on my mac to manage my virtualbox instances.

**Comment by cwarden45** [comment]
I don't think I'm going to be allowed to set up a VM installation, but thanks for the suggestion.  I'll wait see if I can get SMRT Portal access and also wait to see if there is a fix for this particular problem.

**Comment by mhsieh** [comment]
you can install the smrtanalysis in your linux account, that's why I said "starting point" since that vagrant script already reveals how to install a smrtanalysis in local directory with minimal setting.

**Comment by mhsieh** [comment]
I am surprised to learn that you can not even install virtaulbox + vagrant on your Mac by the way, your IT department must have very tight control to restrict vm but allow homebrew.

**Comment by cwarden45** [comment]
Ok - I have access to SMRT Portal now, but it looks like I have a specialized analysis were I may need to use the command-line version of kineticsTools.

Basically, I have 4 samples barcoded in a run and I need to run analysis separately for each barcode.  I can see a barcode protocol and a base modification protocol, but I don't see how I can pipe the result of one protocol to the other.

Right now, I am de-multiplexing the .cmp.h5 file from SMRT Portal using `cmph5tools.py select --groupBy Barcode aligned_reads.cmp.h5`, but I noticed that the full .cmp.h5 file from SMRT Portal also has the same reference error message related to the reference.

**Comment by cwarden45** [comment]
Ok - I figured out the issue for the problem.

The sequence name needed to have a space at the end of it (which was in turn removed by ReferenceUtils.

For my cmp.h5 file, I now get an error message ChemistryLookupError: Chemistry information could not be found in cmp.h5, but I will see if using the SMRT Portal cmp.h5 file helps.  However, the SMRT Portal reference name had some formatting issues (I think because the sequence name had parentheses in it), so I may need to re-produce that file.

Either way, this particular issue is fixed, so I'll close this ticket.
