### ISSUE TITLE
KeyError: 'tMean'

### ISSUE THREAD

**Issue by xogur** [PacificBiosciences/kineticsTools#27]
Hi all, 

I did run the kinecticsTools successfully with single aligned.cmp.h5 file for in-silico control mode. However, I have an error such as "KeyError: tMean" when I run together with the case-control. Could you please share your experience how to solve the issue if you had the same or similar situation? I attached my log at below. Thank you!

Taehyuk

-sh-3.2$ /opt/smrtanalysis/smrtcmds/bin/smrtwrap ipdSummary.py --reference /home/thkang/pDmeth.fa --verbose --outfile ./test/modification --control /opt2/smrtanalysis/userdata/jobs/016/016488/data/aligned_reads.cmp.h5 aligned_reads.cmp.h5
2016-06-23 17:20:19,665 [INFO] Available CPUs: 32
2016-06-23 17:20:19,665 [INFO] Requested worker processes: -1
2016-06-23 17:20:19,695 [INFO] Worker KineticWorkerProcess-2 (PID=23860) started running..................................................................................................................................................................................................................................................................................................................................
2016-06-23 17:33:29,461 [INFO] Process KineticWorkerProcess-10 (PID=23868) done; exiting.
Process KineticsWriter-33:
Traceback (most recent call last):
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/ResultWriter.py", line 102, in run
    self._run()
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/ResultWriter.py", line 87, in _run
    self.onResult(nextChunk)
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/ResultWriter.py", line 860, in onResult
    sink.send(resultChunk)
  File "/opt/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/ResultWriter.py", line 374, in hdf5CsvConsumer
    tMean[idx] = float(x['tMean'])
KeyError: 'tMean'
2016-06-23 17:33:30,131 [ERROR] Child process exited with exitcode=1.  Aborting.

**Comment by casidexiao250** [comment]
hi;
    I noticed that you submitted the question that kinecticsTools can successfully run with single aligned.cmp.h5 file for in-silico control mode, but it will raise error when it run together with the case-control.  Unfortunately，I also encountered the same problem。Have you solved this problem?

casidexiao

**Comment by rhallPB** [comment]
When running with a case control, instead of using the `--outfile` parameter, specify the individual outputs `--gff <gff out> --csv <csv out>`
