### ISSUE TITLE
KeyError: 'IPD'

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/kineticsTools#39]
Hello
I am trying to run kineticsTools on cmp.h5 files which were generated with pbalign the following way:

<pre><code>
pbalign --concordant --hitPolicy=randombest --minAccuracy 70 --minLength 50 --algorithmOptions="-minMatch 12 -bestn 10 -minPctIdentity 70.0" 3rdbtach.fofn longestContig.fasta longestContig_3rdbatch.cmp.h5 --nproc 20  --tmpDir $PWD/TMP 2> 3rdBatch.log &
</code></pre>

If I am trying next to run IpdSummary, as following:

    ipdSummary.py longestContig_3rdbatch.cmp.h5 --reference longestContig.fasta --gff basemods.gff --csv basemods.csv --pvalue 0.05 --numWorkers 16 --identify m4C,m6A --gff basemods.gff

or alternatively with the fewest options

   ipdSummary.py longestContig_3rdbatch.cmp.h5 --reference longestContig.fasta

I encounter the following error:

<pre><code>
Process KineticWorkerProcess-23:
Traceback (most recent call last):
  File "/scratch/local/eschmid/software/smrtanalysis/current/redist/python2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/scratch/local/eschmid/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/WorkerProcess.py", line 108, in run
    self._run()
  File "/scratch/local/eschmid/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/WorkerProcess.py", line 87, in _run
    result = self.onChunk(datum)
  File "/scratch/local/eschmid/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/KineticWorker.py", line 196, in onChunk
    result = self._summarizeReferenceRegion((start, end), self.options.methylFraction, self.options.identify)
  File "/scratch/local/eschmid/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/KineticWorker.py", line 215, in _summarizeReferenceRegion
    (caseChunks, capValue) = self._fetchChunks(caseReferenceGroupId, targetBounds, self.caseCmpH5)
  File "/scratch/local/eschmid/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/KineticWorker.py", line 390, in _fetchChunks
    rawIpds = self._loadRawIpds(hits, start, end, factor)
  File "/scratch/local/eschmid/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/kineticsTools/KineticWorker.py", line 421, in _loadRawIpds
    rawIpd = aln.IPD() * factor
  File "/scratch/local/eschmid/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/CmpH5IO.py", line 188, in f
    return self.pulseFeature(featureName, aligned, orientation)
  File "/scratch/local/eschmid/software/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbcore/io/CmpH5IO.py", line 603, in pulseFeature
    pulseDataset = self.alignmentGroup[featureName]
KeyError: 'IPD'
2016-08-25 08:46:05,373 [ERROR] Child process exited with exitcode=1.  Aborting.
</code></pre>

I encountered this error already earlier when I tried to run pbalign with the --forQuiver option.
As I learned afterwards, this was obviously due to the problem that with this option IPD values are not added to the alignment. But I dont understand why it would generate the error in this case ?
Obviously now I can again add the IPD information afterwards as in this thread [https://github.com/PacificBiosciences/kineticsTools/issues/9](url).
But I really would like to know for once what is the correct way of aligning with pbalign for methylation analysis.
Cheers

**Comment by rhallPB** [comment]
using pbalign `--forQuiver --metrics DeletionQV,IPD,InsertionQV,PulseWidth,QualityValue,MergeQV,SubstitutionQV,DeletionTag`

Alternatively the way it is done internally (SMRT pipe), and likely the most tested method is to add them after the alignment: `loadChemistry.py input.fofn aligned_reads0.cmp.h5
loadPulses input.fofn aligned_reads0.cmp.h5 -metrics DeletionQV,IPD,InsertionQV,PulseWidth,QualityValue,MergeQV,SubstitutionQV,DeletionTag -byread
cmph5tools.py -vv sort --deep --inPlace aligned_reads0.cmp.h5`

**Comment by ebioman** [comment]
Thanks for the swift answer.
I tried 

     pbalign --metrics IPD,DeletionQV,DeletionTag,InsertionQV,MergeQV,SubstitutionQV --concordant --hitPolicy=randombest --minAccuracy 70 --minLength 50 --algorithmOptions="-minMatch 12 -bestn 10 -minPctIdentity 70.0" 3rdbtach.fofn longestContig.fasta  --nproc 20  --tmpDir $PWD/TMP longestContig_3rdbatch.cmp.h5

as described in the Wiki (just saw your answer afterwards) which resulted in the same error. I guess the field "PulseWidth" is the key, or is the order important too ?

Linked to this, what is actually speed wise quicker: running pbalign with the correct options or running loadPulses afterwards ? As well, does it scale for large genomes?

**Comment by rhallPB** [comment]
Order isn't important, but you do need PulseWidth. The code path used is exactly the same no matter how you do it, pbalign itself just runs loadChemistry and loadPulses, so the time is the same. Doing it separately just makes any failures easy to diagnose. How large a genome? you will be relatively safe into the 100's of MB, multi GB is going to cause issues, but mostly likely at the ipdSummary stage.

**Comment by ebioman** [comment]
Thanks, I am facing indeed the multi GB issue - good to know in advance that this might likely fail.
I guess the easiest then will be to do it contig wise instead.
Cheers

**Comment by rhallPB** [comment]
For a very large cmp.h5 I would use cmph5tools.py to subset the alignment by contig before ipdSummary. Each smaller job stands a better chance of completing in a reasonable time.
