### ISSUE TITLE
ipdSummary is hanging at the same point every time I re-run 

### ISSUE THREAD

**Issue by JohnUrban** [PacificBiosciences/kineticsTools#45]
Hi,

kineticsTools is hanging at the same point every time I re-run and consuming more and more memory until it is ultimately canceled.

It fails on the 12th contig is is processing -- and seems to fail at the end of the contig. It doesn't seem to be a size-related thing because previous contigs are larger:
```
tig00000000	1380178
tig00000001	2148377
tig00000002	6134292
tig00000003	1120821
tig00000005	1617830
tig00000006	1800375
tig00000007	3155568
tig00000008	17689
tig00000010	585916
tig00000011	6138856
tig00000014	24309
tig00000016	706149  <- fails/hangs on this contig after writing an entry for position 612189
```

The last 2 lines in basemod.gff are:
```
tig00000016	kinModCall	modified_base	612189	612189	21	-	.	coverage=25;context=TTAGTGATGGGAACCTCAATGATGACTACACAACGATGGAA;IPDRatio=2.16
tig00000016	kinModCall	modified_base
```

The last few lines in kinetics.csv are:
```
"tig00000016",678606,0,G,0,0.734,0.152,1.077,0.682,21,,,
"tig00000016",678606,1,C,0,0.471,0.159,0.725,0.650,17,,,
"tig00000016",678607,0,A,0,0.697,0.192,0.989,0.705,22,,,
"tig00000016",678607,1,T,4,0.707  
```

Given the header ```refName,tpl,strand,base,score,tMean,tErr,modelPrediction,ipdRatio,coverage,frac,fracLow,fracUp```, it looks like it is failing to compute tErr and everything after that.

The command I am using is:
```
ipdSummary ${INPUT} --reference $REF --identify ${IDENTIFY} --methylFraction \
	--gff basemods.gff --csv kinetics.csv --pvalue ${PVALUE} --minCoverage 3 \
	--methylMinCov 10 --identifyMinCov 5 -j ${THREADS} --maxAlignments 1000000 \
	--ms_csv multisite.csv --bigwig ipd.bigWig 
```

Does anyone have any advice on how to move forward? 

Many thanks,

  John

**Comment by rhallPB** [comment]
Unfortunately these kind of bugs are hard to diagnose, can you change the order of the contigs, to move the problem contig to the end? Then rerun, to see if it really is that particular contig and position. Does that contig have unusual read coverage?

**Comment by JohnUrban** [comment]
I will give that a try.

I was also considering processing each contig individually by specifying the ```--refContigs contigName``` flag. Would processing contigs independently like that have any unexpected effects on the results? I wouldn't think so, but I figure it is a question worth asking.

**Comment by rhallPB** [comment]
The calculation is independent across contigs, so using –refContigs should not introduce any problems.

**Comment by JohnUrban** [comment]
I can open a new issue for this if necessary. I found that when I try to do the --refContigs approach, it crashes with a KeyError.

For example:
```
ipdSummary ../out_all.cmp.h5 --reference ../genome.fasta --identify m4C --gff basemods.gff --refContigs tig00000000
```

This is the immediate error:
```
2016-11-19 02:43:59,257 [WARNING] Problem opening reference withIndexedFastaReader
'tig00000001'
Traceback (most recent call last):
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcommand-0.3.29-py2.7.egg/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 719, in args_runner
    return kt.start()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 393, in start
    return self.run()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 455, in run
    ret = self._mainLoop()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 650, in _mainLoop
    self.loadReferenceAndModel(self.args.reference)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 547, in loadReferenceAndModel
    alignmentSet=self.alignments, windows=self.referenceWindows)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ReferenceUtils.py", line 78, in loadReferenceContigs
    contigDict[x.FullName].cmph5ID = x.ID
KeyError: 'tig00000001'
2016-11-19 02:43:59,307 [ERROR] 'tig00000001'
Traceback (most recent call last):
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcommand-0.3.29-py2.7.egg/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 719, in args_runner
    return kt.start()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 393, in start
    return self.run()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 455, in run
    ret = self._mainLoop()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 650, in _mainLoop
    self.loadReferenceAndModel(self.args.reference)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 547, in loadReferenceAndModel
    alignmentSet=self.alignments, windows=self.referenceWindows)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ReferenceUtils.py", line 78, in loadReferenceContigs
    contigDict[x.FullName].cmph5ID = x.ID
KeyError: 'tig00000001'
```

If I use ```--refContigs tig00000000```, the KeyError is 'tig00000001'.
If I use ```--refContigs tig00000001``` or any subsequent contig name, the KeyError is 'tig00000000'.

Do you have any suggestions on how to proceed?

I am going to try switching the order of the contigs as you suggested in the mean time. 

Thanks.

**Comment by rhallPB** [comment]
Looks like a bug in the code, hopefully switching the order of contigs works.

**Comment by JohnUrban** [comment]
Hi @rhallPB 

It was indeed a bug in the code. I mentioned it in issue #46  and @natechols already solved it and pushed the fix to the repo.

I tried ordering the contigs in the fasta file differently, but they are processed in the same order anyway. So for that to work, I would have to change the names so they sort differently I suppose. Perhaps that is what you originally meant. Hopefully, the --refContigs approach now works and I don't have to also try that -- but if I do, I will report back on whether or not it helped.

Thanks for getting back to me.

--John
