### ISSUE TITLE
--refcontigs error

### ISSUE THREAD

**Issue by JohnUrban** [PacificBiosciences/kineticsTools#46]
Hi,

I mentioned recently in issue #12 that ipdSummary was hanging at the end of the same contig every time I re-ran. To potentially circumnavigate that issue, I have been trying to process each contig independently by specifying ```--refContigs contigName``` flag. I found that when I try to do the --refContigs approach, it crashes with a KeyError.

For example:

ipdSummary ../out_all.cmp.h5 --reference ../genome.fasta --identify m4C --gff basemods.gff --refContigs tig00000000

This is the immediate error:
```
2016-11-19 02:43:59,257 [WARNING] Problem opening reference withIndexedFastaReader
'tig00000001'
Traceback (most recent call last):
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcommand-0.3.29-py2.7.egg/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 719, in args_runner
    return kt.start()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 393, in start
    return self.run()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 455, in run
    ret = self._mainLoop()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 650, in _mainLoop
    self.loadReferenceAndModel(self.args.reference)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 547, in loadReferenceAndModel
    alignmentSet=self.alignments, windows=self.referenceWindows)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ReferenceUtils.py", line 78, in loadReferenceContigs
    contigDict[x.FullName].cmph5ID = x.ID
KeyError: 'tig00000001'
2016-11-19 02:43:59,307 [ERROR] 'tig00000001'
Traceback (most recent call last):
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/pbcommand-0.3.29-py2.7.egg/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 719, in args_runner
    return kt.start()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 393, in start
    return self.run()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 455, in run
    ret = self._mainLoop()
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 650, in _mainLoop
    self.loadReferenceAndModel(self.args.reference)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ipdSummary.py", line 547, in loadReferenceAndModel
    alignmentSet=self.alignments, windows=self.referenceWindows)
  File "/users/jurban/software/localpy/lib/python2.7/site-packages/kineticsTools-0.6.0-py2.7-linux-x86_64.egg/kineticsTools/ReferenceUtils.py", line 78, in loadReferenceContigs
    contigDict[x.FullName].cmph5ID = x.ID
KeyError: 'tig00000001'
```

If I use --refContigs tig00000000, the KeyError is 'tig00000001'.
If I use --refContigs tig00000001 or any subsequent contig name, the KeyError is 'tig00000000'.

 I have tried this on multiple dataset so far for different organisms all with the same error. What I am doing is mapping all the reads to all the contigs, merging, sorting, etc -- as one needs to do. Then I am asking ipdSummary to focus only on one contig by specifying ```--refContigs contigName```.

Am I using this option incorrectly?

Does anyone have any suggestions on how to proceed?

Thanks.

--John

**Comment by natechols** [comment]
You're not doing anything wrong, this is just a bug.  I believe this is the fix:

`diff --git a/kineticsTools/ReferenceUtils.py b/kineticsTools/ReferenceUtils.py
index e63758c..ae8a5ab 100755
--- a/kineticsTools/ReferenceUtils.py
+++ b/kineticsTools/ReferenceUtils.py
@@ -75,7 +75,8 @@ class ReferenceUtils():

         # Mark each contig with it's ID from the cmp.h5 - match them up using M
         for x in alignmentSet.referenceInfoTable:
-            contigDict[x.FullName].cmph5ID = x.ID
+            if x.FullName in contigDict:
+                contigDict[x.FullName].cmph5ID = x.ID

         return contigs`

**Comment by JohnUrban** [comment]
Thank you. 
Is that fix going to be pushed to this repository?

**Comment by natechols** [comment]
It certainly could be, but it's just a quick guess and we have no time budgeted to work on kineticsTools development right now, and I don't have an easy way to test it at the moment.  Can you please try it first and see if it actually fixes your problem?  If so I will go ahead and push it.

**Comment by JohnUrban** [comment]
Will do. I appreciate your help.

**Comment by JohnUrban** [comment]
It looks like your quick guess solved the problem.

On a small E.coli test dataset, it gave identical output as processing all the contigs together.
I am running it on a single contig for my larger genome/dataset now and as far as I can tell everything is also working there.

Thanks for your help!

I will close this issue now.
Hopefully you decide to push the change to this repo as I imagine it will help others in the future.

**Comment by AlexWanghaoming** [comment]
Dear @natechols ,
Just as @JohnUrban described long time ago, I met the same questions as #45. But my alignment format is bam.
My command is:
    ipdSummary ../modificationAlignment_sort.bam --reference ../fg_polished.fasta --methylFraction -j 5 --identify m6A,m5C_TET,m4C --gff basemods.gff --csv basemods.csv
The process always hanging at the same point every time I re-run through I use --refContigs parament.
In your commit, it looks like you just make a change for cmp.h5 format.Could you please help me?
Hope you can reply!
yours,
Alex
