### ISSUE TITLE
KeyError: 'FRAMERATEHZ'

### ISSUE THREAD

**Issue by istolarek** [PacificBiosciences/kineticsTools#66]
I have aligned P4C2 pacbio data with blasr
sorted bam file with samtools and indexed with pbindex

after running ipdSummary I get the following error:

'FRAMERATEHZ'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 719, in args_runner
    return kt.start()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 393, in start
    return self.run()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 455, in run
    ret = self._mainLoop()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 626, in _mainLoop
    self.loadSharedAlignmentSet(self.args.alignment_set)
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 602, in loadSharedAlignmentSet
    referenceFastaFname=self.args.reference)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2551, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1876, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 470, in __init__
    self.updateCounts()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2392, in updateCounts
    self.assertIndexed()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2193, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1833, in _assertIndexed
    self._openFiles()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1953, in _openFiles
    resource = IndexedBamReader(location)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 385, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 199, in __init__
    self._loadReadGroupInfo()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 116, in _loadReadGroupInfo
    rgFrameRate = ds["FRAMERATEHZ"]
KeyError: 'FRAMERATEHZ'
2019-03-12 09:32:30,684 [ERROR] 'FRAMERATEHZ'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 719, in args_runner
    return kt.start()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 393, in start
    return self.run()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 455, in run
    ret = self._mainLoop()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 626, in _mainLoop
    self.loadSharedAlignmentSet(self.args.alignment_set)
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 602, in loadSharedAlignmentSet
    referenceFastaFname=self.args.reference)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2551, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1876, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 470, in __init__
    self.updateCounts()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2392, in updateCounts
    self.assertIndexed()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2193, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1833, in _assertIndexed
    self._openFiles()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1953, in _openFiles
    resource = IndexedBamReader(location)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 385, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 199, in __init__
    self._loadReadGroupInfo()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 116, in _loadReadGroupInfo
    rgFrameRate = ds["FRAMERATEHZ"]
KeyError: 'FRAMERATEHZ'

**Comment by OnlyHigh** [comment]
For correcting this error you have to extract ```.bam``` file from ```.bax.h5``` files (please refer to [bax2bam](https://github.com/PacificBiosciences/bax2bam)), then you could use blasr (There other programs to do this) to align the reads against a reference with the previous extracted bam as input reads.
