### ISSUE TITLE
ipdSummary error "M5"

### ISSUE THREAD

**Issue by jgonzalez10** [PacificBiosciences/kineticsTools#67]
Hi, I'm having trouble with ipdSummary too. The error I'm getting it the following: 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 719, in args_runner
    return kt.start()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 393, in start
    return self.run()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 455, in run
    ret = self._mainLoop()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 626, in _mainLoop
    self.loadSharedAlignmentSet(self.args.alignment_set)
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 602, in loadSharedAlignmentSet
    referenceFastaFname=self.args.reference)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2551, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1876, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 470, in __init__
    self.updateCounts()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2392, in updateCounts
    self.assertIndexed()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2193, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1833, in _assertIndexed
    self._openFiles()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1953, in _openFiles
    resource = IndexedBamReader(location)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 385, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 198, in __init__
    self._loadReferenceInfo()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 73, in _loadReferenceInfo
    refMD5s    = [r["M5"] for r in refRecords]
KeyError: 'M5'
2019-05-15 15:55:15,219 [ERROR] 'M5'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 719, in args_runner
    return kt.start()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 393, in start
    return self.run()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 455, in run
    ret = self._mainLoop()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 626, in _mainLoop
    self.loadSharedAlignmentSet(self.args.alignment_set)
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ipdSummary.py", line 602, in loadSharedAlignmentSet
    referenceFastaFname=self.args.reference)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2551, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1876, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 470, in __init__
    self.updateCounts()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2392, in updateCounts
    self.assertIndexed()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 2193, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1833, in _assertIndexed
    self._openFiles()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/dataset/DataSetIO.py", line 1953, in _openFiles
    resource = IndexedBamReader(location)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 385, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 198, in __init__
    self._loadReferenceInfo()
  File "/usr/lib/python2.7/dist-packages/pbcore/io/align/BamIO.py", line 73, in _loadReferenceInfo
    refMD5s    = [r["M5"] for r in refRecords]
KeyError: 'M5'

Does somebody know what's happening??? Heeelp please!!!
Thanks!!!!

**Comment by natechols** [comment]
How was the aligned BAM file generated?

**Comment by jgonzalez10** [comment]
Hi,

As far as I know with Blasr.





Juliana González Tobón
Estudiante Biología y Microbiología
Laboratorio de Micología y Fitopatología (LAMFU)
Universidad de los Andes
Bogotá, Colombia

On May 15, 2019, at 10:59 AM, Nat Echols <notifications@github.com<mailto:notifications@github.com>> wrote:


How was the aligned BAM file generated?

**Comment by natechols** [comment]
Which version of Blasr, and what was the full command?

**Comment by jgonzalez10** [comment]
Sorry, I already checked and they were done with pbmm2, an interface of minimap2 used to align PacBio reads along with the kinetics info. I don’t have the exact command because this is a multi person project and I’m just in charge of the base modificactions analysis. Can you help me?





Juliana González Tobón
Estudiante Biología y Microbiología
Laboratorio de Micología y Fitopatología (LAMFU)
Universidad de los Andes
Bogotá, Colombia

On May 15, 2019, at 11:23 AM, Nat Echols <notifications@github.com<mailto:notifications@github.com>> wrote:


Which version of Blasr, and what was the full command?

**Comment by natechols** [comment]
I think you need to update to the latest pbcore - the M5 requirement has been removed there.

**Comment by jgonzalez10** [comment]
And how can I do that?




Juliana González Tobón
Estudiante Biología y Microbiología
Laboratorio de Micología y Fitopatología (LAMFU)
Universidad de los Andes
Bogotá, Colombia

On May 15, 2019, at 4:14 PM, Nat Echols <notifications@github.com<mailto:notifications@github.com>> wrote:


I think you need to update to the latest pbcore - the M5 requirement has been removed there.

**Comment by natechols** [comment]
This depends on how pbcore is installed.  I recommend using the pbbioconda distribution: https://github.com/PacificBiosciences/pbbioconda

**Comment by jgonzalez10** [comment]
I installed all the smrtlink suite in a virtual machine. Therefore I would need a way tu update that. Unless you are suggesting me to install this via conda and try and use it instead of smrtlink?
