### ISSUE TITLE
ImportError: No module named pyBigWig

### ISSUE THREAD

**Issue by liufeibio** [PacificBiosciences/kineticsTools#70]
Hi, there
I run the ipdsummary programme, but got an error: ImportError: No module named pyBigWig.
I have installed it via conda, but still got this error. Could you help me with it? Thanks!
``
ipdSummary ./raw.bam --reference ../quickmerge/merged.pyscaf.fasta --gff basemods.gff --csv kinetics.csv --bigwig IpdRatio.bw --identify m6A,m4C,m5C_TET --methylFraction --numWorkers 10 --minCoverage 3
``
this is error indicated:
``
Process KineticsWriter-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ResultWriter.py", line 112, in run
    self._run()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ResultWriter.py", line 70, in _run
    self.onStart()
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ResultWriter.py", line 941, in onStart
    sinkList.append(func(name))
  File "/usr/lib/python2.7/dist-packages/kineticsTools/pipelineTools.py", line 35, in start
    next(c)
  File "/usr/lib/python2.7/dist-packages/kineticsTools/ResultWriter.py", line 284, in bigWigConsumer
    import pyBigWig
ImportError: No module named pyBigWig
Child process exited with exitcode=1.  Aborting.
2019-12-11 12:43:20,630 [ERROR] Child process exited with exitcode=1.  Aborting.
``

**Comment by rhallPB** [comment]
Have you tried installing pybigwig independently? `conda install -c bioconda pybigwig`

**Comment by liufeibio** [comment]
yes, I have tried that

**Comment by natechols** [comment]
I don't understand how this error can happen if you have actually installed the module.  What happens when you run `python -c "import pyBigWig"`, using the bioconda python?

**Comment by rhallPB** [comment]
I notice the install is in your system path, you may want to try installing and running everything in a fresh conda environment, [https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html](url)

**Comment by liufeibio** [comment]
> I don't understand how this error can happen if you have actually installed the module. What happens when you run `python -c "import pyBigWig"`, using the bioconda python?

it is like this:
``
(pbalign) sujitmaiti@sujitmaiti-MS-7885:~/biosoftware/kineticsTools$ python
Python 2.7.15 | packaged by conda-forge | (default, Nov 29 2018, 06:43:57)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyBigWig
>>>

``

**Comment by natechols** [comment]
I think @rhallPB has the right idea, you may have installed kineticsTools into the wrong Python.

**Comment by liufeibio** [comment]
> I think @rhallPB has the right idea, you may have installed kineticsTools into the wrong Python.

I am creating a new conda environment for kineticsTools with python=2.7, am I using a right version of python? Thanks!

**Comment by liufeibio** [comment]
> > I think @rhallPB has the right idea, you may have installed kineticsTools into the wrong Python.
> 
> I am creating a new conda environment for kineticsTools with python=2.7, am I using a right version of python? Thanks!

I found that the code (print(delim.join(cols), file=f)) in ResultsWriter.py seems to be written in Python3? So I should use python3? Thanks  for your answer.

**Comment by natechols** [comment]
No, because it's a compatibility function for Python 2:
https://github.com/PacificBiosciences/kineticsTools/blob/master/kineticsTools/ResultWriter.py#L1
The next release of kineticsTools *will* switch to Python 3, however.  (No, I don't have an ETA for this.)
