### ISSUE TITLE
Stop at the same region of genome with OSError

### ISSUE THREAD

**Issue by DustinChen1986** [PacificBiosciences/kineticsTools#86]
Hi,
I got bam with pbmm2 v1.3.0.
`pbmm2 align ref.mmi mymovies.fofn pbmm2.bam --sort`
Then I used kineticsTools:
`ipdSummary pbmm2.bam --reference genome.fasta --identify m6A,m4C --methylFraction --gff kinetics.gff --csv kinetics.csv --bigwig kinetics.bw --log-level INFO  --numWorkers 12 --referenceStride 100000`
ipdSummary started with:

> [INFO] 2021-04-21 03:17:29,441Z [kineticsTools.ipdSummary _pacbio_main_runner 160] Using pbcommand v2.2.2
[INFO] 2021-04-21 03:17:29,442Z [kineticsTools.ipdSummary _pacbio_main_runner 161] completed setting up logger with <function setup_log at 0x7f1005654f70>
[INFO] 2021-04-21 03:17:29,443Z [kineticsTools.ipdSummary _pacbio_main_runner 164] log opts {'level': 20, 'file_name': None}
[INFO] 2021-04-21 03:17:29,516Z [root loadSharedAlignmentSet 475] Reading AlignmentSet: pbmm2.bam
[INFO] 2021-04-21 03:17:29,516Z [root loadSharedAlignmentSet 476]            reference: /mnt/hgfs/G/1.Pacbio/genome.fasta
[WARNING] 2021-04-21 03:17:31,050Z [pbcore.io.dataset.DataSetIO _openFiles 2162] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[WARNING] 2021-04-21 03:17:34,395Z [pbcore.io.dataset.DataSetIO _openFiles 2162] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:17:35,728Z [kineticsTools.loader getIpdModelFilename 42] Using chemistry-matched kinetics model: '/usr/local/lib/python3.8/dist-packages/kineticsTools-0.7.0-py3.8-linux-x86_64.egg/kineticsTools/resources/SP2-C2.npz.gz'
[INFO] 2021-04-21 03:17:35,728Z [root loadReferenceAndModel 463] Loading reference contigs '/mnt/hgfs/G/1.Pacbio/genome.fasta'
[INFO] 2021-04-21 03:18:04,974Z [root _launchSlaveProcesses 410] Available CPUs: 12
[INFO] 2021-04-21 03:18:04,974Z [root _launchSlaveProcesses 411] Requested worker processes: 12
[INFO] 2021-04-21 03:18:04,996Z [root _run 90] Worker KineticWorkerProcess-1 (PID=45444) started running
[INFO] 2021-04-21 03:18:05,003Z [root _run 90] Worker KineticWorkerProcess-2 (PID=45445) started running
[INFO] 2021-04-21 03:18:05,010Z [root _run 90] Worker KineticWorkerProcess-3 (PID=45446) started running
[INFO] 2021-04-21 03:18:05,018Z [root _run 90] Worker KineticWorkerProcess-4 (PID=45447) started running
[INFO] 2021-04-21 03:18:05,024Z [root _run 90] Worker KineticWorkerProcess-5 (PID=45448) started running
[INFO] 2021-04-21 03:18:05,031Z [root _run 90] Worker KineticWorkerProcess-6 (PID=45449) started running
[INFO] 2021-04-21 03:18:05,037Z [root _run 90] Worker KineticWorkerProcess-7 (PID=45450) started running
[INFO] 2021-04-21 03:18:05,050Z [root _run 90] Worker KineticWorkerProcess-8 (PID=45451) started running
[INFO] 2021-04-21 03:18:05,056Z [root _run 90] Worker KineticWorkerProcess-9 (PID=45452) started running
[INFO] 2021-04-21 03:18:05,059Z [root _run 90] Worker KineticWorkerProcess-10 (PID=45453) started running
[INFO] 2021-04-21 03:18:05,067Z [root _run 90] Worker KineticWorkerProcess-11 (PID=45454) started running
[INFO] 2021-04-21 03:18:05,072Z [root _launchSlaveProcesses 437] Launched worker processes.
[INFO] 2021-04-21 03:18:05,081Z [root _launchSlaveProcesses 443] Launched result collector process.
[INFO] 2021-04-21 03:18:05,082Z [root _run 90] Worker KineticWorkerProcess-12 (PID=45455) started running
[INFO] 2021-04-21 03:18:05,083Z [root _mainLoop 540] Generating kinetics summary for [pbmm2.bam]
[INFO] 2021-04-21 03:18:05,083Z [root _mainLoop 555] Processing window/contig: ReferenceWindow(refId=0, refName='Chr1', start=0, end=44929686)
[INFO] 2021-04-21 03:18:05,083Z [kineticsTools.ResultWriter _run 40] Process KineticsWriter-13 (PID=45456) started running
[INFO] 2021-04-21 03:18:07,180Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:07,185Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:07,196Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:07,197Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:07,198Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:07,199Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:07,201Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:07,201Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:07,201Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:07,208Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:07,208Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:07,209Z [root _openFiles 36] pbi file missing for /mnt/hgfs/G/1.Pacbio/pbmm2.bam, operating with reduced speed and functionality
[INFO] 2021-04-21 03:18:10,187Z [root _run 125] Got chunk: (0, ReferenceWindow(refId=0, refName='Chr1', start=0, end=1000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-2' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,187Z [root _run 125] Got chunk: (1, ReferenceWindow(refId=0, refName='Chr1', start=1000, end=2000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-4' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,187Z [root _run 125] Got chunk: (2, ReferenceWindow(refId=0, refName='Chr1', start=2000, end=3000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-6' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,187Z [root _run 125] Got chunk: (3, ReferenceWindow(refId=0, refName='Chr1', start=3000, end=4000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-12' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,187Z [root _run 125] Got chunk: (4, ReferenceWindow(refId=0, refName='Chr1', start=4000, end=5000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-8' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,187Z [root _run 125] Got chunk: (6, ReferenceWindow(refId=0, refName='Chr1', start=6000, end=7000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-9' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,188Z [root _run 125] Got chunk: (5, ReferenceWindow(refId=0, refName='Chr1', start=5000, end=6000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-5' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,188Z [root _run 125] Got chunk: (7, ReferenceWindow(refId=0, refName='Chr1', start=7000, end=8000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-10' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,189Z [root _summarizeReferenceRegion 226] Making summary: -15 to 1015
[INFO] 2021-04-21 03:18:10,189Z [root _summarizeReferenceRegion 226] Making summary: 2985 to 4015
[INFO] 2021-04-21 03:18:10,190Z [root _summarizeReferenceRegion 226] Making summary: 1985 to 3015
[INFO] 2021-04-21 03:18:10,190Z [root _summarizeReferenceRegion 226] Making summary: 985 to 2015
[INFO] 2021-04-21 03:18:10,190Z [root _summarizeReferenceRegion 226] Making summary: 3985 to 5015
[INFO] 2021-04-21 03:18:10,190Z [root _summarizeReferenceRegion 226] Making summary: 4985 to 6015
[INFO] 2021-04-21 03:18:10,191Z [root _summarizeReferenceRegion 226] Making summary: 5985 to 7015
[INFO] 2021-04-21 03:18:10,191Z [root _summarizeReferenceRegion 226] Making summary: 6985 to 8015
[INFO] 2021-04-21 03:18:10,193Z [root _run 125] Got chunk: (8, ReferenceWindow(refId=0, refName='Chr1', start=8000, end=9000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-3' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,194Z [root _run 125] Got chunk: (9, ReferenceWindow(refId=0, refName='Chr1', start=9000, end=10000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-7' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,196Z [root _summarizeReferenceRegion 226] Making summary: 7985 to 9015
[INFO] 2021-04-21 03:18:10,197Z [root _summarizeReferenceRegion 226] Making summary: 8985 to 10015
[INFO] 2021-04-21 03:18:10,198Z [root _run 125] Got chunk: (10, ReferenceWindow(refId=0, refName='Chr1', start=10000, end=11000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-1' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,200Z [root _summarizeReferenceRegion 226] Making summary: 9985 to 11015
[INFO] 2021-04-21 03:18:10,201Z [root _run 125] Got chunk: (11, ReferenceWindow(refId=0, refName='Chr1', start=11000, end=12000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-11' parent=45419 started daemon>
[INFO] 2021-04-21 03:18:10,210Z [root _summarizeReferenceRegion 226] Making summary: 10985 to 12015
[INFO] 2021-04-21 03:18:10,387Z [root _fetchChunks 426] Retrieved 23 hits
[INFO] 2021-04-21 03:18:10,417Z [root _fetchChunks 426] Retrieved 31 hits
[INFO] 2021-04-21 03:18:10,423Z [root _fetchChunks 426] Retrieved 26 hits
[INFO] 2021-04-21 03:18:10,438Z [root _fetchChunks 426] Retrieved 39 hits
[INFO] 2021-04-21 03:18:10,449Z [root _fetchChunks 426] Retrieved 45 hits
[INFO] 2021-04-21 03:18:10,487Z [root _fetchChunks 426] Retrieved 50 hits
[INFO] 2021-04-21 03:18:10,534Z [root _fetchChunks 426] Retrieved 54 hits
[INFO] 2021-04-21 03:18:10,538Z [root _fetchChunks 426] Retrieved 57 hits
[INFO] 2021-04-21 03:18:10,564Z [root _fetchChunks 426] Retrieved 48 hits
[INFO] 2021-04-21 03:18:10,573Z [root _fetchChunks 426] Retrieved 56 hits
[INFO] 2021-04-21 03:18:10,648Z [root _fetchChunks 426] Retrieved 56 hits
[INFO] 2021-04-21 03:18:10,693Z [root _fetchChunks 426] Retrieved 59 hits
...

Then I encounter the following error at the same genome region for some times:

>[INFO] 2021-04-23 01:47:10,480Z [root _run 125] Got chunk: (167, ReferenceWindow(refId=0, refName='Chr1', start=1670000, end=1680000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-12' parent=95111 started daemon>
[INFO] 2021-04-23 01:47:10,863Z [root _summarizeReferenceRegion 226] Making summary: 1669985 to 1680015
[INFO] 2021-04-23 01:47:11,395Z [root _fetchChunks 426] Retrieved 92 hits
[INFO] 2021-04-23 01:47:12,097Z [root _run 125] Got chunk: (168, ReferenceWindow(refId=0, refName='Chr1', start=1680000, end=1690000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-9' parent=95111 started daemon>
[INFO] 2021-04-23 01:47:12,433Z [root _summarizeReferenceRegion 226] Making summary: 1679985 to 1690015
[INFO] 2021-04-23 01:47:12,946Z [root _run 125] Got chunk: (169, ReferenceWindow(refId=0, refName='Chr1', start=1690000, end=1700000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-1' parent=95111 started daemon>
[INFO] 2021-04-23 01:47:12,961Z [root _summarizeReferenceRegion 226] Making summary: 1689985 to 1700015
Process KineticWorkerProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/kineticsTools-0.7.0-py3.8-linux-x86_64.egg/kineticsTools/WorkerProcess.py", line 151, in run
    self._run()
  File "/usr/local/lib/python3.8/dist-packages/kineticsTools-0.7.0-py3.8-linux-x86_64.egg/kineticsTools/WorkerProcess.py", line 127, in _run
    result = self.onChunk(
  File "/usr/local/lib/python3.8/dist-packages/kineticsTools-0.7.0-py3.8-linux-x86_64.egg/kineticsTools/KineticWorker.py", line 121, in onChunk
    perSiteResults = self._summarizeReferenceRegion(
  File "/usr/local/lib/python3.8/dist-packages/kineticsTools-0.7.0-py3.8-linux-x86_64.egg/kineticsTools/KineticWorker.py", line 230, in _summarizeReferenceRegion
    (caseChunks, capValue) = self._fetchChunks(
  File "/usr/local/lib/python3.8/dist-packages/kineticsTools-0.7.0-py3.8-linux-x86_64.egg/kineticsTools/KineticWorker.py", line 421, in _fetchChunks
    hits = [hit for hit in alignmentFile.readsInRange(refGroupId,
  File "/usr/local/lib/python3.8/dist-packages/kineticsTools-0.7.0-py3.8-linux-x86_64.egg/kineticsTools/KineticWorker.py", line 421, in <listcomp>
    hits = [hit for hit in alignmentFile.readsInRange(refGroupId,
  File "/usr/local/lib/python3.8/dist-packages/pbcore-2.3.1-py3.8.egg/pbcore/io/dataset/DataSetIO.py", line 3469, in <genexpr>
    return (read for read in self._readsInRange(refName, start, end,
  File "/usr/local/lib/python3.8/dist-packages/pbcore-2.3.1-py3.8.egg/pbcore/io/dataset/DataSetIO.py", line 179, in wrapper
    for read in generator(dset, *args, **kwargs):
  File "/usr/local/lib/python3.8/dist-packages/pbcore-2.3.1-py3.8.egg/pbcore/io/dataset/DataSetIO.py", line 3556, in _readsInRange
    for read in resource.readsInRange(refName, start, end):
  File "/usr/local/lib/python3.8/dist-packages/pbcore-2.3.1-py3.8.egg/pbcore/io/align/BamIO.py", line 383, in <genexpr>
    return (BamAlignment(self, it)
  File "pysam/libcalignmentfile.pyx", line 2086, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file
[INFO] 2021-04-23 01:47:14,637Z [root _run 125] Got chunk: (170, ReferenceWindow(refId=0, refName='Chr1', start=1700000, end=1710000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-4' parent=95111 started daemon>
Child process exited with exitcode=1.  Aborting.
[ERROR] 2021-04-23 01:47:14,872Z [root monitorChildProcesses 592] Child process exited with exitcode=1.  Aborting.

Would you help me to fix it?
Thank you for your replication.

**Comment by rhallPB** [comment]
The output suggests an issue with the aligned bam file, the first thing to check would be to generate the pbi index file for the bam [https://pbbam.readthedocs.io/en/latest/tools/pbindex.html](url) to see if this solves the issue.
