### ISSUE TITLE
Child process exited with exitcode=1.  Aborting.

### ISSUE THREAD

**Issue by GaoChengyu** [PacificBiosciences/kineticsTools#90]
Hi
I use ipdSummary to detect 6ma. but i meet a error.
`Process KineticWorkerProcess-4:
Traceback (most recent call last):
  File "/home/gaocy/miniconda3/envs/genome/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/gaocy/miniconda3/envs/genome/lib/python3.9/site-packages/kineticsTools-0.8.0-py3.9-linux-x86_64.egg/kineticsTools/WorkerProcess.py", line 151, in run
    self._run()
  File "/home/gaocy/miniconda3/envs/genome/lib/python3.9/site-packages/kineticsTools-0.8.0-py3.9-linux-x86_64.egg/kineticsTools/WorkerProcess.py", line 127, in _run
    result = self.onChunk(  # pylint: disable=assignment-from-none
  File "/home/gaocy/miniconda3/envs/genome/lib/python3.9/site-packages/kineticsTools-0.8.0-py3.9-linux-x86_64.egg/kineticsTools/KineticWorker.py", line 121, in onChunk
    perSiteResults = self._summarizeReferenceRegion(
  File "/home/gaocy/miniconda3/envs/genome/lib/python3.9/site-packages/kineticsTools-0.8.0-py3.9-linux-x86_64.egg/kineticsTools/KineticWorker.py", line 230, in _summarizeReferenceRegion
    (caseChunks, capValue) = self._fetchChunks(
  File "/home/gaocy/miniconda3/envs/genome/lib/python3.9/site-packages/kineticsTools-0.8.0-py3.9-linux-x86_64.egg/kineticsTools/KineticWorker.py", line 432, in _fetchChunks
    hits = np.random.choice(
  File "mtrand.pyx", line 901, in numpy.random.mtrand.RandomState.choice
  File "/home/gaocy/miniconda3/envs/genome/lib/python3.9/site-packages/pbcore-2.4.0-py3.9.egg/pbcore/io/align/BamAlignment.py", line 68, in f
    raise UnavailableFeature(
pbcore.io.align._BamSupport.UnavailableFeature: this feature requires a PacBio BAM index
[INFO] 2022-01-15 07:26:46,816Z [root _run 125] Got chunk: (33061, ReferenceWindow(refId=7, refName='scaffold8', start=2345000, end=2346000)) -- Process: <KineticWorkerProcess name='KineticWorkerProcess-5' parent=13610 started daemon>
[INFO] 2022-01-15 07:26:46,833Z [root _summarizeReferenceRegion 226] Making summary: 2344985 to 2346015
Child process exited with exitcode=1.  Aborting.`
My genome fasta file has 36 contigs. When i use ipdSummary to detect contig1 to contig7, everything is OK. but when ipdSummary run contig 8, the error occurred. 
Maybe i can get help from you.
thank you very much!

**Comment by liuweiming1** [comment]
Hello, have you solved this problem?
