### ISSUE TITLE
ipdSummary: AssertionError Child process exited with exitcode=1

### ISSUE THREAD

**Issue by anikajohn** [PacificBiosciences/kineticsTools#92]
Hi,

I am having trouble running ipdSummary (SMRTLINK version 11.0.0146107) although I am (presumingly) using all the right inputs.
Reads were produced with Sequel II sequencer. 
 
This is the command I am running:
`/usr/prog/GX/tools/src/pacbio/smrtlink/v11.0/smrtcmds/bin/ipdSummary aligned.bam --reference reference.fa --identify m6A --gff basemods.gff`

Which gives me the following error:
`Process KineticWorkerProcess-1:
Traceback (most recent call last):
  File "/usr/prog/GX/tools/src/pacbio/smrtlink/v11.0/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/prog/GX/tools/src/pacbio/smrtlink/v11.0/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/kineticsTools/WorkerProcess.py", line 151, in run
    self._run()
  File "/usr/prog/GX/tools/src/pacbio/smrtlink/v11.0/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/kineticsTools/WorkerProcess.py", line 127, in _run
    result = self.onChunk(  # pylint: disable=assignment-from-none
  File "/usr/prog/GX/tools/src/pacbio/smrtlink/v11.0/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/kineticsTools/KineticWorker.py", line 121, in onChunk
    perSiteResults = self._summarizeReferenceRegion(
  File "/usr/prog/GX/tools/src/pacbio/smrtlink/v11.0/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/kineticsTools/KineticWorker.py", line 230, in _summarizeReferenceRegion
    (caseChunks, capValue) = self._fetchChunks(
  File "/usr/prog/GX/tools/src/pacbio/smrtlink/v11.0/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/kineticsTools/KineticWorker.py", line 449, in _fetchChunks
    rawIpds = self._loadRawIpds(hits, start, end, factor)
  File "/usr/prog/GX/tools/src/pacbio/smrtlink/v11.0/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/kineticsTools/KineticWorker.py", line 484, in _loadRawIpds
    rawIpd = aln.IPD() * factor
  File "/usr/prog/GX/tools/src/pacbio/smrtlink/v11.0/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/pbcore/io/align/BamAlignment.py", line 49, in f
    return self.baseFeature(featureName, aligned, orientation)
  File "/usr/prog/GX/tools/src/pacbio/smrtlink/v11.0/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/pbcore/io/align/BamAlignment.py", line 536, in baseFeature
    assert len(data) == self.peer.rlen
AssertionError
Child process exited with exitcode=1.  Aborting.
[ERROR] 2022-04-28 10:55:32,038Z [root monitorChildProcesses 592] Child process exited with exitcode=1.  Aborting.`

I alinged my reads using pbmm2:
`pbmm2 align reference.fa kinetic_reads.bam aligned.bam --sort`

I also tried it with a 0.3 subset of my bam files, but it still gave the same error message. Feedback would be much appreciated, thanks already!

**Comment by anikajohn** [comment]
In case my set up is not suitable for this ipdSummary, I would also be happy about suggestions for alternative/better tools with similar functionalities. I am mainly interested in the detection of 6mA modified bases.
