### ISSUE TITLE
ValueError: invalid literal for int() with base 16: 'myid'

### ISSUE THREAD

**Issue by tongyin121** [PacificBiosciences/kineticsTools#94]
Hi, I got an problem when I ran ipdsummary, and here is the error:
invalid literal for int() with base 16: 'myid'
Traceback (most recent call last):
  File "/usr_storage/zyl/software/smrtlink/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/pbcore/io/dataset/DataSetIO.py", line 2171, in _openFiles
    resource = IndexedBamReader(location)
  File "/usr_storage/zyl/software/smrtlink/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/pbcore/io/align/BamIO.py", line 400, in __init__
    super().__init__(fname, referenceFastaFname)
  File "/usr_storage/zyl/software/smrtlink/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/pbcore/io/align/BamIO.py", line 197, in __init__
    self._loadReadGroupInfo()
  File "/usr_storage/zyl/software/smrtlink/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/pbcore/io/align/BamIO.py", line 86, in _loadReadGroupInfo
    rgID = rgAsInt(rg["ID"])
  File "/usr_storage/zyl/software/smrtlink/install/smrtlink-release_11.0.0.146107/bundles/smrttools/install/smrttools-release_11.0.0.146107/private/thirdparty/python3/python3_3.9.6/site-packages/pbcore/io/align/_BamSupport.py", line 66, in rgAsInt
    return np.int32(int(rgIdString.split("/")[0], 16))
ValueError: invalid literal for int() with base 16: 'myid'
Would you help me to fix it?
Thank you for your replication.

**Comment by wshuai294** [comment]
Hello, I met a similar issue. How was it solved?
